modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[dependencies.maniacmod]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.maniacmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.maniacmod]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.maniacmod]]
    modId="playeranimator"
    mandatory=true
    versionRange="[1.0.2, )"
    ordering="AFTER"
    side="BOTH"

[[dependencies.maniacmod]]
    modId="shaurma_lib"
    mandatory=true
    versionRange="[0.1,)"
    ordering="AFTER"
    side="BOTH"

[[mods]]
modId="maniacmod"
version="3.0.0"
displayName="Maniac Mod"
description='''
Повноцінна гра Маньяк для Minecraft 1.20+
Чакі (0.5 бл) та Слендермен (4 бл) з реальними хітбоксами.
'''
